### ISSUE TITLE
TypeScript types got broken by this project installation 

### ISSUE THREAD

**Issue by ColCh** [TypeStrong/fork-ts-checker-webpack-plugin#107]
We have pure-FrontEnd project, but after this project install, we have strange errors about Timer type, like this.

```
src/foo.ts(85,13): error TS2322: Type 'Timer' is not assignable to type 'number'.

85             this.timeout = setTimeout(loop, 0);
               ~~~~~~~~~~~~

```

this is because of node typings installed.

```
~/W/foo $ stat node_modules/@types/node/
16777220 8595635200 drwxr-xr-x 7 colch Users 0 224 "Mar 23 14:24:40 2018" "Mar 23 14:24:47 2018" "Mar 23 14:24:47 2018" "Mar 23 14:24:40 2018" 4194304 0 0 node_modules/@types/node/
```

these typings got installed because of this chain:

```
~/W/foo $ yarn why @types/node/
yarn why v1.5.1
warning package.json: No license field
[1/4] 🤔  Why do we have the module "@types/node/"...?
[2/4] 🚚  Initialising dependency graph...
warning yandex-pcode@0.0.1: No license field
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@types/node@9.4.6"
info Reasons this module exists
   - "fork-ts-checker-webpack-plugin#vue-parser#parse5" depends on it
   - Hoisted from "fork-ts-checker-webpack-plugin#vue-parser#parse5#@types#node"
info Disk size without dependencies: "20MB"
info Disk size with unique dependencies: "20MB"
info Disk size with transitive dependencies: "20MB"
info Number of shared dependencies: 0
✨  Done in 1.24s.
```

So, the question is, why `vue-parser` exists in `dependencies` anyway? We have no `vue` in project installed anyway, as well as react.

It seems that this introduced by https://github.com/Realytics/fork-ts-checker-webpack-plugin/pull/77

**Comment by johnnyreilly** [comment]
If you use `window.setTimeout` does that work?

**Comment by ColCh** [comment]
Thank you for your answer. Yes, it does. It's a proposed solution?

I wonder if there is possibility to remove node typings from project if it's not used actually

**Comment by johnnyreilly** [comment]
They're only `devDependencies` aren't they? Shouldn't being impacting you?

**Comment by ColCh** [comment]
Sorry but what do you mean about `devDependencies`?

`vue-parser` is listed in regular `dependencies` section https://github.com/Realytics/fork-ts-checker-webpack-plugin/blob/master/package.json#L96

And `fork-ts-checker-webpack-plugin` - yes, it's development dependency. But we can't build project because TS errors

**Comment by johnnyreilly** [comment]
Oh  sorry I misunderstood you. `vue-parser` is in play for Vue support. @prograhammer can likely advise why.

I'm unclear why `vue-parser` would have `@types/node` as a dependency but then I don't use Vue so it's not really my area ...

**Comment by ColCh** [comment]
May be just make `vue-parser` as `peerDependency` ? I can send PR. What do you think @prograhammer @johnnyreilly ?
