### ISSUE TITLE
Type errors:  'exports' has no exported member named 'compilation'. Did you mean 'Compilation'?

### ISSUE THREAD

**Issue by revmischa** [TypeStrong/fork-ts-checker-webpack-plugin#685]
## Current behavior
```
node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPlugin.d.ts:4:61 - error TS2694: Namespace 'exports' has no exported member 'Plugin'.

4 declare class ForkTsCheckerWebpackPlugin implements webpack.Plugin {
                                                              ~~~~~~

node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPlugin.d.ts:21:113 - error TS2724: 'exports' has no exported member named 'compilation'. Did you mean 'Compilation'?

21         start: import("tapable").AsyncSeriesWaterfallHook<import("./reporter/FilesChange").FilesChange, webpack.compilation.Compilation, any>;
                                                                                                                   ~~~~~~~~~~~

node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPlugin.d.ts:22:53 - error TS2724: 'exports' has no exported member named 'compilation'. Did you mean 'Compilation'?

22         waiting: import("tapable").SyncHook<webpack.compilation.Compilation, any, any>;
                                                       ~~~~~~~~~~~

node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPlugin.d.ts:23:54 - error TS2724: 'exports' has no exported member named 'compilation'. Did you mean 'Compilation'?

23         canceled: import("tapable").SyncHook<webpack.compilation.Compilation, any, any>;
                                                        ~~~~~~~~~~~

node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPlugin.d.ts:24:58 - error TS2724: 'exports' has no exported member named 'compilation'. Did you mean 'Compilation'?

24         error: import("tapable").SyncHook<Error, webpack.compilation.Compilation, any>;
                                                            ~~~~~~~~~~~

node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPlugin.d.ts:25:94 - error TS2724: 'exports' has no exported member named 'compilation'. Did you mean 'Compilation'?

25         issues: import("tapable").SyncWaterfallHook<import("./issue/Issue").Issue[], webpack.compilation.Compilation | undefined, void>;
                                                                                                ~~~~~~~~~~~
```

## Environment

I'm using ES modules, maybe that makes a difference?

 - **fork-ts-checker-webpack-plugin**: 6.5.0
 - **typescript**: 4.4.4
 - **webpack**: 5.65.0
 - **os**: macOS

**Comment by piotr-oles** [comment]
Hi! Could you test with v7.0.0? We switched to a newer typings (by dropping webpack 4 support)

**Comment by piotr-oles** [comment]
Did it help?

**Comment by revmischa** [comment]
Hm I got it working some time ago with v6.5.0, not sure how. When I upgrade to v7 I don't see any output, seems like webpack just hangs. If I downgrade back to 6.5.0 then webpack builds fine with the checker

**Comment by piotr-oles** [comment]
Ok, I'm closing this issue then :)
